name:        zkp
version:     0.1.0
synopsis:    Zero Knowledge Proof Protocol
description: Zero Knowledge Proof Protocol
homepage:    https://github.com/adjoint-io/zkp#readme
author:      Adjoint Inc.
license:     AllRightsReserved
maintainer:  stephen@adjoint.io
copyright:   2016-2020 Adjoint Inc
category:    Cryptography

extra-source-files:
  - README.md
  - ChangeLog.md

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - StandaloneDeriving
  - GADTs
dependencies:
  # Base
  - base        >= 4.12  && <4.14
  - protolude   >= 0.2.4 && <0.3
  - text        >= 1.2   && <2.0
  - vector      >= 0.12.0 && < 0.13
  - bytestring  >= 0.10.8 && < 0.11
  - containers  >= 0.6.0 && < 0.7
  - mtl         >= 2.2.2 && < 2.3
  - aeson       >= 1.4.0 && < 1.5
  - directory   >= 1.3.3 && < 1.4
  - filepath    >= 1.4.2 && < 1.5

  # Algebra
  - semirings   >= 0.5.0 && < 0.6
  - groups      >= 0.4.1 && < 0.5
  - poly        >= 0.3.2 && < 0.4

  # Cryptography
  - galois-field         >= 1.0.0 && < 1.1
  - galois-fft           >= 0.1.0 && < 0.2
  - elliptic-curve       >= 0.3.0 && < 0.4
  - pairing              >= 1.0.0 && < 1.1
  - arithmetic-circuits  >= 0.2.0 && < 0.3
  - crypto-numbers       >= 0.2.7 && < 0.3
  - SHA                  >= 1.6.4 && < 1.7
  - entropy              >= 0.4.1 && < 0.5

  # Libraries
  - criterion            >= 1.5.0 && < 1.6
  - generic-arbitrary    >= 0.1.0 && < 0.2
  - QuickCheck           >= 2.12.0 && < 2.14
  - wl-pprint-text       >= 1.2.0 && < 1.3
  - pretty-simple        >= 2.0   && < 3.3

library:
  source-dirs: src
  exposed-modules:
    - Protocol.Groth
  other-modules:
    - Poly

tests:
  test-zkp:
    main: Test.hs
    source-dirs:
      - test
    dependencies:
      - zkp
      - QuickCheck
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-quickcheck
    ghc-options:
      - -Wall
      - -Wno-name-shadowing
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

executables:
  zkp:
    main: Main.hs
    source-dirs: exe
    other-modules: 
      - Setup
      - Prove
      - Verify
      - Reference
    dependencies:
      - zkp
      - galois-field
      - optparse-applicative
    ghc-options:
      - -Wall
      - -Wno-name-shadowing
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
